apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yaqlu2fwq-nodejs 
  janus-idp.io/tekton: yaqlu2fwq-nodejs
  backstage.io/kubernetes-id: yaqlu2fwq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yaqlu2fwq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml